### PR TITLE
Dev architecture

### LINKED ISSUE #23: Learn about and build a solid coding architecture for the app

### PR DESCRIPTION
**Pull request by WollfieGitHub**
The architecture is based on [this page](https://farhan-tanvir.medium.com/clean-architecture-in-android-jetpack-compose-kotlin-mvvm-%E3%83%BCpart-1-f17908b83c0d) which is linked to [this repo](https://github.com/Farhandroid/AndroidCleanArchitecture/tree/Part-2) and can be revisited as we learn to use it.

The User, Book and Author objects are basic objects which regroups what I've seen from the API's response and what I could think of. Feel free to comment on any property/field we might want to add to these class skeletons

Closes #23 and #20

### CODE REVIEW

**Review by Lynoxe — CHANGES_REQUESTED** [review]
The beta kotlin version prevents the Continuous Integration to work correctly, we should use 1.7.0

**Comment by WollfieGitHub** [comment]
> The beta kotlin version prevents the Continuous Integration to work correctly, we should use 1.7.0

I had the same message from my IDE but I'm confused as to where I should change this ?

**Comment by WollfieGitHub** [comment]
> The beta kotlin version prevents the Continuous Integration to work correctly, we should use 1.7.0

You already changed this in the commit 4917a1df83b7ffd4c2004d13f2da1092663c0445 right ?

**Comment by Lynoxe** [comment]
> 

Yes I did, sorry that I reviewed after it wasn't the best move

**Comment by Lynoxe** [comment]
What is the difference between the domain folder and the data folder? In particular why are there test folders in data?

**Comment by WollfieGitHub** [comment]
> What is the difference between the domain folder and the data folder? In particular why are there test folders in data? And what is _paging_ ?

The domain folder would contain everything related to our application's model : Books, Ratings, etc.. and the interactions between these elements.
The data folder would contain everything related to HOW we get the data for a particular element (Local cached database, Remote database, API call to a third party library...)

Paging is an Android library which allows to load chunks of data on-demand. It was included in the architecture and was talked about as being "good practice" but if it increases code complexity we can get rid of it I think, I'll do further research on this
The documentation [is here](https://developer.android.com/topic/libraries/architecture/paging) if need be

**Review by Lynoxe — APPROVED** [review]

**Pull request merged**
